/* eslint-disable */
/* tslint:disable */
import { z } from 'zod';

// ===== Zod Schema =====

/**
 * Generated by orval v8.5.3 🍺
 * Do not edit manually.
 * Pet Store
 * OpenAPI spec version: 1.0.0
 */
export const listPetsQueryParams = z.object({
  limit: z.number().optional(),
});

export const listPetsHeader = z.object({
  Authorization: z.string(),
  "X-Request-Id": z.string().optional(),
});

export const listPetsResponseItem = z.object({
  id: z.number(),
  name: z.string(),
  tag: z.string().optional(),
});
export const listPetsResponse = z.array(listPetsResponseItem);

export const createPetBody = z.object({
  name: z.string(),
  tag: z.string().optional(),
});

export const getPetByIdParams = z.object({
  petId: z.string(),
});

export const getPetByIdResponse = z.object({
  id: z.number(),
  name: z.string(),
  tag: z.string().optional(),
});


// ===== Operations =====

/**
 * Unified operations artifact — single source of truth for runtime validation
 * AND TypeScript types.
 *
 * Runtime validation:
 *   new HttpProtocol({ schema: operations })
 *
 * Explicit-generic typing:
 *   new HttpProtocol<typeof operations>()
 */
export const operations = {
  listPets: {
    request: z.object({
      method: z.literal('GET'),
      path: z.literal('/pets'),
      body: z.never().optional(),
      query: listPetsQueryParams.optional(),
      headers: listPetsHeader.optional(),
    }),
    response: z.object({ code: z.literal(200), body: listPetsResponse }),
  },
  createPet: {
    request: z.object({
      method: z.literal('POST'),
      path: z.literal('/pets'),
      body: createPetBody,
    }),
    response: z.object({ code: z.literal(201), body: z.never().optional() }),
  },
  getPetById: {
    request: z.object({
      method: z.literal('GET'),
      path: z.string(),
      body: z.never().optional(),
    }),
    response: z.object({ code: z.literal(200), body: getPetByIdResponse }),
  },
};

// ===== Service Type (derived) =====

export type PetStore = {
  [K in keyof typeof operations]: {
    request: z.infer<(typeof operations)[K]["request"]>;
    response: z.infer<(typeof operations)[K]["response"]>;
  };
};

// ===== Type Helpers =====

export type PetStoreOperations = typeof operations;
export type PetStoreOperationId = keyof PetStore;
