import { mkdir, writeFile } from 'node:fs/promises';
import path from 'node:path';
import type { GeneratedFile, Logger } from '../generators/types.js';

function createFileHeader(sourcePath: string): string {
  const timestamp = new Date().toISOString();
  return `/* eslint-disable */
/* tslint:disable */
/**
 * AUTO-GENERATED by testurio generate
 * Source: ${sourcePath}
 * DO NOT EDIT MANUALLY
 *
 * Generated: ${timestamp}
 */

`;
}

export async function writeGeneratedFiles(
  files: GeneratedFile[],
  sourcePath: string,
  logger: Logger,
): Promise<void> {
  const header = createFileHeader(sourcePath);

  for (const file of files) {
    const dir = path.dirname(file.path);
    await mkdir(dir, { recursive: true });

    const content = header + file.content;
    await writeFile(file.path, content, 'utf-8');
    logger.success(`Generated: ${file.path}`);
  }
}
