/**
 * Kafka Adapter
 *
 * Main adapter implementing IMQAdapter for Kafka using KafkaJS. Per task 037
 * v5.8 this adapter is a **factory** — every `createSubscriber()` call mints a
 * fresh `KafkaSubscriberAdapter` (typically one per test case under per-TC
 * isolation). Adapter-wide subscribe-time defaults live on
 * `config.defaultSubscribeParams`; per-call overrides flow through
 * `ev.subscribe('topic', { ... })` at the builder.
 */

import { Kafka, logLevel as KafkaLogLevel } from "kafkajs";
import {
	type Codec,
	defaultJsonCodec,
	type IMQAdapter,
	type IMQPublisherAdapter,
	type IMQSubscriberAdapter,
	type QueueMessage,
} from "testurio";
import { KafkaPublisherAdapter } from "./kafka.publisher.adapter";
import { KafkaSubscriberAdapter } from "./kafka.subscriber.adapter";
import type { KafkaAdapterConfig, KafkaSubscribeParams, KafkaSubscriberAdapterOptions } from "./kafka.types";
import { randomSuffix } from "./util";

/**
 * Kafka adapter for testurio MQ components.
 *
 * @example Zero-config per-TC isolation (recommended)
 * ```typescript
 * const kafka = new KafkaAdapter({ brokers: ["localhost:9092"] });
 * const events = new Subscriber("events", { adapter: kafka });
 * // Each test case gets a unique consumer group `testurio-<random>` automatically.
 * ```
 *
 * @example Shared groupId across test cases (opt-in)
 * ```typescript
 * const kafka = new KafkaAdapter({
 *   brokers: ["localhost:9092"],
 *   defaultSubscribeParams: { groupId: "shared-events", fromBeginning: true },
 * });
 * ```
 */
export class KafkaAdapter implements IMQAdapter<QueueMessage, unknown, unknown, KafkaSubscribeParams> {
	readonly type = "kafka";
	private readonly kafka: Kafka;
	private readonly config: KafkaAdapterConfig;
	private publishers: KafkaPublisherAdapter[] = [];
	/** v5.7 (H7) — Set, O(1) add/remove via the subscriber's `onClose` callback. */
	private readonly subscribers = new Set<KafkaSubscriberAdapter>();
	/**
	 * v5.7 (C3) — every auto-generated groupId issued during the scenario.
	 * Swept via one shared admin client at `dispose()`. User-provided groupIds
	 * are never tracked here and never deleted by the framework.
	 */
	private readonly _autoGeneratedGroupIds = new Set<string>();

	constructor(config: KafkaAdapterConfig) {
		this.config = config;

		// Apply test mode optimizations for faster connections
		const testModeKafkaConfig = config.testMode
			? {
					connectionTimeout: 3000, // 3s (default: 30s)
					requestTimeout: 5000, // 5s (default: 30s)
					enforceRequestTimeout: true,
					retry: {
						initialRetryTime: 100,
						retries: 3,
						maxRetryTime: 1000,
					},
				}
			: {};

		this.kafka = new Kafka({
			clientId: config.clientId ?? "testurio-kafka-adapter",
			brokers: config.brokers,
			connectionTimeout: config.connectionTimeout ?? 30000,
			requestTimeout: config.requestTimeout ?? 30000,
			ssl: config.ssl,
			sasl: config.sasl,
			logLevel: config.logLevel ?? KafkaLogLevel.WARN,
			...testModeKafkaConfig,
			...config.kafkaOptions,
		});
	}

	async createPublisher(codec: Codec = defaultJsonCodec): Promise<IMQPublisherAdapter> {
		const producer = this.kafka.producer(this.config.producerOptions);
		const adapter = new KafkaPublisherAdapter(producer, codec);
		await adapter.connect();
		this.publishers.push(adapter);
		return adapter;
	}

	/**
	 * Create a fresh subscriber adapter. Reads adapter-wide defaults from
	 * `config.defaultSubscribeParams`. Auto-generates `testurio-${randomSuffix(8)}`
	 * when no `groupId` is provided so each test case (one `createSubscriber`
	 * per TC) gets its own consumer group by default.
	 */
	async createSubscriber(
		codec: Codec = defaultJsonCodec
	): Promise<IMQSubscriberAdapter<QueueMessage, KafkaSubscribeParams>> {
		const defaults = this.config.defaultSubscribeParams;
		const autoGenerated = defaults?.groupId === undefined;
		const effectiveGroupId = defaults?.groupId ?? `testurio-${randomSuffix(8)}`;
		if (autoGenerated) {
			this._autoGeneratedGroupIds.add(effectiveGroupId);
		}

		// Apply test mode optimizations for faster consumer coordination
		const testModeConfig = this.config.testMode
			? {
					heartbeatInterval: 500, // 500ms (default: 3000ms)
					sessionTimeout: 6000, // 6s (default: 30000ms)
					rebalanceTimeout: 10000, // 10s (default: 60000ms)
					maxWaitTimeInMs: 100, // 100ms (default: 5000ms)
					metadataMaxAge: 1000, // 1s (default: 300_000ms) — refresh metadata aggressively so freshly auto-created topics' partition assignments propagate to the fetcher within test budgets (BUG-007).
					minBytes: 1,
					maxBytes: 1048576,
					retry: {
						initialRetryTime: 100,
						retries: 5,
						maxRetryTime: 1000,
						factor: 0.2,
					},
				}
			: {};

		const consumer = this.kafka.consumer({
			groupId: effectiveGroupId,
			...testModeConfig,
			...this.config.consumerOptions,
		});

		const joinTimeoutMs = this.config.groupJoinTimeoutMs ?? (this.config.testMode ? 5000 : 30000);
		const options: KafkaSubscriberAdapterOptions = {
			kafka: this.kafka,
			groupId: effectiveGroupId,
			autoGeneratedGroupId: autoGenerated,
			defaultFromBeginning: defaults?.fromBeginning,
			consumerOptions: { ...testModeConfig, ...this.config.consumerOptions },
			joinTimeoutMs,
			onClose: (a) => this.removeSubscriber(a),
		};
		const adapter = new KafkaSubscriberAdapter(consumer, codec, options);
		await adapter.connect();
		this.subscribers.add(adapter);
		return adapter;
	}

	private removeSubscriber(adapter: KafkaSubscriberAdapter): void {
		this.subscribers.delete(adapter);
	}

	/**
	 * Dispose adapter resources. Closes any subscribers still alive (defensive
	 * — `Subscriber.doStop` should have closed them all), sweeps every
	 * auto-generated consumer group from the broker via one shared admin
	 * client, then closes all publishers.
	 *
	 * Auto-generated groupIds: deleted best-effort — any per-group failure is
	 * logged via `console.warn` and ignored. By scenario teardown the long
	 * tail of LeaveGroup processing has typically completed, so the race
	 * window is small.
	 *
	 * User-provided (explicit) groupIds are NEVER deleted by the framework.
	 */
	async dispose(): Promise<void> {
		// (a) close any subscribers still alive
		if (this.subscribers.size > 0) {
			const aliveSubscribers = Array.from(this.subscribers);
			await Promise.allSettled(aliveSubscribers.map((s) => s.close()));
		}

		// (b) sweep auto-generated groupIds via one shared admin client
		if (this._autoGeneratedGroupIds.size > 0) {
			const admin = this.kafka.admin();
			try {
				await admin.connect();
				try {
					await admin.deleteGroups([...this._autoGeneratedGroupIds]);
				} catch (err) {
					console.warn(
						`KafkaAdapter.dispose: deleteGroups partial failure: ${err instanceof Error ? err.message : String(err)}`
					);
				}
			} finally {
				await admin.disconnect();
			}
			this._autoGeneratedGroupIds.clear();
		}

		// (c) close publishers (existing behavior preserved)
		for (const publisher of this.publishers) {
			await publisher.close();
		}
		this.publishers = [];
	}
}
