/**
 * Kafka Subscriber Adapter
 *
 * Implements `IMQSubscriberAdapter<QueueMessage, KafkaSubscribeParams>` for
 * KafkaJS. Supports batched subscribe/unsubscribe, transparent restart on new
 * topics after the consumer is already running, and per-TC isolation when
 * driven by the v5.8 `Subscriber` component.
 */

import type { Consumer, ConsumerConfig, ConsumerCrashEvent, EachMessagePayload, Kafka } from "kafkajs";
import type { Codec, IMQSubscriberAdapter, QueueMessage } from "testurio";
import { ConsumerJoinTimeoutError } from "./kafka.errors";
import type { KafkaMessageMetadata, KafkaSubscribeParams, KafkaSubscriberAdapterOptions } from "./kafka.types";

/**
 * Kafka subscriber adapter.
 *
 * **v5.8 contract changes vs master**:
 * - `subscribe(topic | topics, params?)` activates the consume loop on first
 *   call (folds in master's separate `startConsuming` step).
 * - Adding topics after activation triggers a disconnect-reconnect restart
 *   that preserves per-topic `fromBeginning` for already-active topics.
 * - `close()` is idempotent (`_closed` flag).
 */
export class KafkaSubscriberAdapter implements IMQSubscriberAdapter<QueueMessage, KafkaSubscribeParams> {
	readonly id: string;
	private _isConnected = false;
	private _isRunning = false;
	/** v5.7 (M4) — idempotency flag for `close()`. */
	private _closed = false;

	private messageHandler?: (topic: string, message: QueueMessage) => void;
	private errorHandler?: (error: Error) => void;
	private disconnectHandler?: () => void;

	/** Every topic Kafka knows about on this consumer. */
	private readonly kafkaSubscribed = new Set<string>();
	/** Subset currently active (soft-unsubscribe removes from here only). */
	private readonly activeTopics = new Set<string>();
	/**
	 * Recorded only for topics introduced by an EXPLICIT subscribe call.
	 * Auto-subscribe (component passes `undefined`) does NOT populate this map.
	 */
	private readonly _topicSubscribeParams = new Map<string, KafkaSubscribeParams>();

	private consumer: Consumer;
	private readonly codec: Codec;
	private readonly _kafka: Kafka;
	private readonly _groupId: string;
	private readonly _autoGeneratedGroupId: boolean;
	private readonly _defaultFromBeginning: boolean;
	private readonly _consumerOptions: Omit<ConsumerConfig, "groupId"> | undefined;
	private readonly _joinTimeoutMs: number;
	private readonly _onClose: ((adapter: KafkaSubscriberAdapter) => void) | undefined;

	constructor(consumer: Consumer, codec: Codec, options: KafkaSubscriberAdapterOptions) {
		this.consumer = consumer;
		this.codec = codec;
		this._kafka = options.kafka;
		this._groupId = options.groupId;
		this._autoGeneratedGroupId = options.autoGeneratedGroupId;
		this._defaultFromBeginning = options.defaultFromBeginning ?? false;
		this._consumerOptions = options.consumerOptions;
		this._joinTimeoutMs = options.joinTimeoutMs ?? 30_000;
		this._onClose = options.onClose;
		this.id = `kafka-sub-${this._groupId}-${Date.now()}-${Math.random().toString(36).slice(2, 9)}`;
	}

	get isConnected(): boolean {
		return this._isConnected;
	}

	/** Auto-generated groupId flag — exposed for the parent adapter's sweep. */
	get autoGeneratedGroupId(): boolean {
		return this._autoGeneratedGroupId;
	}

	/** Effective groupId — exposed for the parent adapter's sweep. */
	get groupId(): string {
		return this._groupId;
	}

	/**
	 * Connect to Kafka. Idempotent — second call is a no-op.
	 */
	async connect(): Promise<void> {
		if (this._isConnected) return;
		await this.consumer.connect();
		this._isConnected = true;
	}

	/**
	 * Subscribe to one or more topics. Activates the consume loop on first
	 * call. Idempotent per topic — already-known topics are no-ops at the
	 * broker level. Per-call `params` are recorded for the topic on the first
	 * EXPLICIT call; subsequent explicit calls with a different value warn
	 * via `console.warn` (Kafka semantics: `fromBeginning` only applies on
	 * the initial subscribe of a topic per consumer).
	 *
	 * @param topic - Single topic or array of topics
	 * @param params - Optional per-call overrides (Partial<KafkaSubscribeParams>)
	 */
	async subscribe(topic: string | string[], params?: Partial<KafkaSubscribeParams>): Promise<void> {
		const isExplicit = params !== undefined;
		const fromBeginning = params?.fromBeginning ?? this._defaultFromBeginning;
		const inputTopics = Array.isArray(topic) ? topic : [topic];

		const newToKafka: string[] = [];
		for (const t of inputTopics) {
			if (this.kafkaSubscribed.has(t)) {
				if (isExplicit) {
					const recorded = this._topicSubscribeParams.get(t);
					if (recorded === undefined) {
						// Topic was auto-subscribed earlier; first explicit call wins. Record.
						this._topicSubscribeParams.set(t, { fromBeginning });
					} else if (recorded.fromBeginning !== fromBeginning) {
						// Second explicit call with a conflicting value — warn.
						console.warn(
							`KafkaSubscriberAdapter.subscribe: per-call fromBeginning=${fromBeginning} ignored on topic '${t}' ` +
								`(first explicit subscribe used fromBeginning=${recorded.fromBeginning}). ` +
								"Kafka semantics: fromBeginning only takes effect on the initial subscribe of a topic per consumer."
						);
					}
				}
				if (!this.activeTopics.has(t)) {
					// Soft-unsubscribed earlier — re-activate without a broker call.
					this.activeTopics.add(t);
				}
				continue;
			}
			newToKafka.push(t);
			if (isExplicit) {
				this._topicSubscribeParams.set(t, { fromBeginning });
			}
			// Auto-subscribe case: deliberately leave `_topicSubscribeParams[t]`
			// empty so the first later explicit call wins.
		}

		if (newToKafka.length === 0) return;

		if (this._isRunning) {
			await this.restartConsumerWithTopics(newToKafka, fromBeginning);
		} else {
			await this.consumer.subscribe({ topics: newToKafka, fromBeginning });
			await this.startInternalRun();
		}
		for (const t of newToKafka) {
			this.kafkaSubscribed.add(t);
			this.activeTopics.add(t);
		}
	}

	/**
	 * Soft-unsubscribe: remove the topic(s) from `activeTopics`. Kafka itself
	 * does not support per-topic unsubscribe on a running consumer, so we
	 * filter inbound messages on the receive path instead.
	 */
	async unsubscribe(topic: string | string[]): Promise<void> {
		const inputTopics = Array.isArray(topic) ? topic : [topic];
		for (const t of inputTopics) this.activeTopics.delete(t);
	}

	getSubscribedTopics(): string[] {
		return [...this.activeTopics];
	}

	onMessage(handler: (topic: string, message: QueueMessage) => void): void {
		this.messageHandler = handler;
	}

	onError(handler: (error: Error) => void): void {
		this.errorHandler = handler;

		// Also surface KafkaJS consumer crashes through the user handler.
		this.consumer.on("consumer.crash", (event: ConsumerCrashEvent) => {
			handler(event.payload.error);
		});
	}

	onDisconnect(handler: () => void): void {
		this.disconnectHandler = handler;

		this.consumer.on("consumer.disconnect", () => {
			this._isConnected = false;
			handler();
		});
	}

	/**
	 * Restart the consumer to pick up new topics added after `consumer.run()`
	 * was already activated. KafkaJS does not document `consumer.stop()` as a
	 * public API, so we use disconnect + new consumer + reconnect, then
	 * replay every still-active topic grouped by its per-topic `fromBeginning`
	 * (auto-subscribed topics use the adapter's default; explicit ones use
	 * the value recorded at first explicit subscribe). New topics are
	 * appended in their own `consumer.subscribe` call with the requested
	 * `fromBeginning`, then `run()` re-activates the consume loop.
	 */
	private async restartConsumerWithTopics(newTopics: string[], newFromBeginning: boolean): Promise<void> {
		await this.consumer.disconnect();
		this._isRunning = false;
		// Replace the consumer instance — same groupId, same consumerOptions.
		this.consumer = this._kafka.consumer({
			groupId: this._groupId,
			...(this._consumerOptions ?? {}),
		});
		await this.consumer.connect();

		// Replay already-active (NON-new) topics grouped by fromBeginning.
		const groups = new Map<boolean, string[]>();
		for (const t of this.activeTopics) {
			const fb = this._topicSubscribeParams.get(t)?.fromBeginning ?? this._defaultFromBeginning;
			const list = groups.get(fb) ?? [];
			list.push(t);
			groups.set(fb, list);
		}
		for (const [fb, topics] of groups) {
			await this.consumer.subscribe({ topics, fromBeginning: fb });
		}
		// New topics — separate call with the requested fromBeginning.
		await this.consumer.subscribe({ topics: newTopics, fromBeginning: newFromBeginning });

		await this.startInternalRun();
	}

	/**
	 * Activate `consumer.run()` and await BOTH `GROUP_JOIN` AND the first
	 * `FETCH_START` so subsequently-published messages on subscribed topics
	 * will be delivered.
	 *
	 * `GROUP_JOIN` fires after SyncGroup completes (partitions assigned), but
	 * kafkajs computes each partition's initial fetch offset asynchronously
	 * after that. For `auto.offset.reset = latest` (`fromBeginning: false`),
	 * a publish landing between GROUP_JOIN and the first FetchRequest commit
	 * advances the HWM and the offset commits past the publish — the message
	 * is silently dropped. Awaiting `FETCH_START` closes that race because it
	 * fires only after the initial offset has been committed and the fetcher
	 * has issued its first FetchRequest.
	 *
	 * The FETCH_START wait is bounded by a 2 s ceiling for edge cases where it
	 * never fires (empty/zero-partition topic at JoinGroup, topic that doesn't
	 * exist until the first publish creates it). In those cases the race
	 * window is closed by other means (next metadata refresh or first-publish
	 * topic creation) and proceeding without FETCH_START is correct.
	 *
	 * Rejects with `ConsumerJoinTimeoutError` if GROUP_JOIN does not fire
	 * within the configured join timeout (default 30 s; override via
	 * `KafkaSubscriberAdapterOptions.joinTimeoutMs`).
	 */
	private async startInternalRun(): Promise<void> {
		if (this._isRunning) return;
		const timeoutMs = this._joinTimeoutMs;
		let joinTimer: ReturnType<typeof setTimeout> | undefined;
		let fetchTimer: ReturnType<typeof setTimeout> | undefined;
		let removeJoinListener: (() => void) | undefined;
		let removeFetchListener: (() => void) | undefined;
		const joinPromise = new Promise<void>((resolve, reject) => {
			removeJoinListener = this.consumer.on(this.consumer.events.GROUP_JOIN, () => {
				resolve();
			});
			joinTimer = setTimeout(() => {
				reject(new ConsumerJoinTimeoutError(timeoutMs));
			}, timeoutMs);
		});
		// Bounded fetch wait — 2 s safety ceiling. FETCH_START fires once the
		// first FetchRequest is issued for any assigned partition, which is
		// when kafkajs has committed the initial offset and a publish landing
		// after this point cannot race past the consumer's seek position.
		const fetchPromise = Promise.race<void>([
			new Promise<void>((resolve) => {
				removeFetchListener = this.consumer.on(this.consumer.events.FETCH_START, () => {
					resolve();
				});
			}),
			new Promise<void>((resolve) => {
				fetchTimer = setTimeout(resolve, 2000);
			}),
		]);
		try {
			// Whichever rejects first (consumer.run throwing OR the join timeout)
			// surfaces to the caller; the surviving promises are GC'd cleanly
			// because the timers are cleared and the listeners removed in `finally`.
			await Promise.all([
				this.consumer.run({
					eachMessage: async (payload: EachMessagePayload) => {
						await this.handleMessage(payload);
					},
				}),
				joinPromise,
				fetchPromise,
			]);
			this._isRunning = true;
		} finally {
			if (joinTimer) clearTimeout(joinTimer);
			if (fetchTimer) clearTimeout(fetchTimer);
			removeJoinListener?.();
			removeFetchListener?.();
		}
	}

	private async handleMessage(payload: EachMessagePayload): Promise<void> {
		if (!this.messageHandler) return;
		// Soft-unsubscribe filter — topic may be in kafkaSubscribed but not active.
		if (!this.activeTopics.has(payload.topic)) return;

		try {
			const { topic, partition, message } = payload;

			// Decode headers
			const headers: Record<string, string> = {};
			if (message.headers) {
				for (const [key, value] of Object.entries(message.headers)) {
					if (value) {
						headers[key] = Buffer.isBuffer(value) ? value.toString() : String(value);
					}
				}
			}

			// Decode payload — pass raw Buffer to the codec; wire-format
			// normalization (text vs binary) is the codec's responsibility.
			const decodedPayload = message.value ? await this.codec.decode(message.value) : null;

			const metadata: KafkaMessageMetadata = {
				partition,
				offset: message.offset,
				size: message.size,
				attributes: message.attributes,
			};

			const queueMessage: QueueMessage = {
				topic,
				payload: decodedPayload,
				key: message.key?.toString(),
				headers: Object.keys(headers).length > 0 ? headers : undefined,
				timestamp: message.timestamp ? Number.parseInt(message.timestamp, 10) : undefined,
				metadata,
			};

			this.messageHandler(topic, queueMessage);
		} catch (error) {
			this.errorHandler?.(error instanceof Error ? error : new Error(String(error)));
		}
	}

	/**
	 * v5.7 (C3 + M4) — idempotent. Disconnects the consumer; group cleanup is
	 * deferred to `KafkaAdapter.dispose()` (one shared admin sweep of
	 * `_autoGeneratedGroupIds`). Safe to call from both `Subscriber.clearHooks`
	 * (per-TC teardown) and `Subscriber.doStop` (scenario teardown).
	 */
	async close(): Promise<void> {
		if (this._closed) return;
		this._closed = true;
		if (this._isRunning) {
			this._isRunning = false;
		}
		if (this._isConnected) {
			try {
				await this.consumer.disconnect();
			} finally {
				this._isConnected = false;
				this.disconnectHandler?.();
			}
		}
		this.activeTopics.clear();
		this.kafkaSubscribed.clear();
		this._topicSubscribeParams.clear();
		this._onClose?.(this);
	}
}
