/**
 * Kafka Adapter Types
 *
 * Configuration and type definitions for the Kafka MQ adapter.
 */

import type { ConsumerConfig, KafkaConfig, logLevel, ProducerConfig } from "kafkajs";

/**
 * Per-subscribe params for Kafka (passed through `Subscriber.subscribe(topic, params)`
 * AND used as adapter-wide defaults via `KafkaAdapterConfig.defaultSubscribeParams`).
 *
 * Both fields are optional. The semantics around `groupId` are intentionally
 * tuned for per-test-case isolation:
 *
 * - Provided explicitly on `defaultSubscribeParams.groupId`: every test case's
 *   per-TC subscriber adapter is constructed with that fixed groupId — all
 *   test cases share one Kafka consumer group and compete for partitions on
 *   shared topics (Kafka semantics).
 * - Omitted: the framework auto-generates `testurio-${randomSuffix(8)}` per
 *   `createSubscriber()` call so every test case gets a unique consumer
 *   group. **This is the recommended default.**
 *
 * `fromBeginning` is honored at `consumer.subscribe({ topic, fromBeginning })`
 * time. Per-call override via `ev.subscribe('topic', { fromBeginning: true })`
 * is supported; the first explicit value per topic wins under Kafka semantics
 * (`fromBeginning` only affects the initial subscribe of a topic per consumer).
 */
export interface KafkaSubscribeParams {
	/**
	 * Consumer group ID. Optional — omit to get auto-generated per-TC groupId.
	 */
	groupId?: string;
	/**
	 * Whether new topic subscriptions read from the beginning of the topic.
	 * Defaults to `false` when omitted.
	 */
	fromBeginning?: boolean;
}

/**
 * Kafka adapter configuration
 */
export interface KafkaAdapterConfig {
	/**
	 * Kafka broker addresses
	 * @example ["localhost:9092", "localhost:9093"]
	 */
	brokers: string[];

	/**
	 * Client ID for this adapter instance
	 * @default "testurio-kafka-adapter"
	 */
	clientId?: string;

	/**
	 * Adapter-wide defaults for `KafkaSubscriberAdapter` instances spawned by
	 * this adapter. Used by every `createSubscriber()` call (i.e. every test
	 * case in the default per-TC isolation mode).
	 *
	 * Per-call subscribe-level overrides flow through
	 * `ev.subscribe('topic', { fromBeginning: true })` and override the
	 * per-topic field at subscribe time.
	 *
	 * **v5.8 BREAKING vs master**: the top-level `groupId` and `fromBeginning`
	 * fields are removed. Migration:
	 * `new KafkaAdapter({ brokers, groupId, fromBeginning })`
	 * → `new KafkaAdapter({ brokers, defaultSubscribeParams: { groupId, fromBeginning } })`.
	 */
	defaultSubscribeParams?: KafkaSubscribeParams;

	/**
	 * Connection timeout in milliseconds
	 * @default 30000
	 */
	connectionTimeout?: number;

	/**
	 * Request timeout in milliseconds
	 * @default 30000
	 */
	requestTimeout?: number;

	/**
	 * SSL/TLS configuration
	 */
	ssl?: boolean | KafkaConfig["ssl"];

	/**
	 * SASL authentication configuration
	 */
	sasl?: KafkaConfig["sasl"];

	/**
	 * Log level for KafkaJS
	 * @default logLevel.WARN
	 */
	logLevel?: logLevel;

	/**
	 * Additional KafkaJS configuration options
	 */
	kafkaOptions?: Partial<KafkaConfig>;

	/**
	 * Producer-specific configuration
	 */
	producerOptions?: ProducerConfig;

	/**
	 * Consumer-specific configuration
	 */
	consumerOptions?: Omit<ConsumerConfig, "groupId">;

	/**
	 * Enable test mode with optimized timeouts for faster consumer coordination.
	 * Reduces sessionTimeout to 6s and rebalanceTimeout to 10s.
	 *
	 * Use this in integration tests to speed up consumer group coordination.
	 *
	 * @default false
	 */
	testMode?: boolean;

	/**
	 * Maximum time (in milliseconds) that the Kafka subscriber adapter will
	 * wait for the `consumer.events.GROUP_JOIN` event before rejecting with
	 * `ConsumerJoinTimeoutError`. Applies to both the initial subscribe-time
	 * activation and to the disconnect-reconnect restart path used when new
	 * topics are added after the consumer is already running.
	 *
	 * @default 30000 (5000 when `testMode` is enabled)
	 */
	groupJoinTimeoutMs?: number;
}

/**
 * Constructor options for `KafkaSubscriberAdapter`. Replaces the v5.6 anonymous
 * object literal in `KafkaAdapter.createSubscriber` — keeps the field set
 * documented and discoverable from a single named type.
 */
export interface KafkaSubscriberAdapterOptions {
	/**
	 * Kafka client. Held by the subscriber adapter so it can mint a fresh
	 * `Consumer` during the disconnect-reconnect restart path triggered by
	 * adding a new topic to an already-running consumer.
	 */
	kafka: import("kafkajs").Kafka;
	/** Resolved consumer group id (auto-generated or user-provided). */
	groupId: string;
	/**
	 * Whether `groupId` was auto-generated by the framework. The parent
	 * `KafkaAdapter` tracks auto-generated ids in `_autoGeneratedGroupIds`
	 * and sweeps them via one shared admin client at `dispose()` time.
	 */
	autoGeneratedGroupId: boolean;
	/**
	 * Default `fromBeginning` value used when a topic is subscribed without
	 * an explicit per-call override (Phase 1.5 auto-subscribe path).
	 */
	defaultFromBeginning?: boolean;
	/**
	 * Consumer config carried over from the parent `KafkaAdapter` (used when
	 * rebuilding the consumer during the restart path).
	 */
	consumerOptions?: Omit<ConsumerConfig, "groupId">;
	/** Optional GROUP_JOIN timeout override (default 30 s). */
	joinTimeoutMs?: number;
	/**
	 * Called from `close()` after `consumer.disconnect()` so the parent
	 * adapter can deregister this subscriber from its registry.
	 */
	onClose?: (adapter: import("./kafka.subscriber.adapter").KafkaSubscriberAdapter) => void;
}

/**
 * Kafka message metadata
 *
 * Broker-specific metadata returned with received messages.
 * Use this interface to interpret QueueMessage.metadata.
 */
export interface KafkaMessageMetadata {
	/**
	 * Partition the message was received from
	 */
	partition: number;

	/**
	 * Offset of the message in the partition
	 */
	offset: string;

	/**
	 * Size of the message in bytes
	 */
	size?: number;

	/**
	 * Message attributes
	 */
	attributes?: number;
}

/**
 * Type guard to check if metadata is Kafka metadata
 */
export function isKafkaMetadata(metadata: unknown): metadata is KafkaMessageMetadata {
	return (
		typeof metadata === "object" &&
		metadata !== null &&
		"partition" in metadata &&
		"offset" in metadata &&
		typeof (metadata as KafkaMessageMetadata).partition === "number" &&
		typeof (metadata as KafkaMessageMetadata).offset === "string"
	);
}

/**
 * Extract Kafka partition from message metadata
 */
export function getKafkaPartition(metadata: unknown): number | undefined {
	if (isKafkaMetadata(metadata)) {
		return metadata.partition;
	}
	return undefined;
}

/**
 * Extract Kafka offset from message metadata
 */
export function getKafkaOffset(metadata: unknown): string | undefined {
	if (isKafkaMetadata(metadata)) {
		return metadata.offset;
	}
	return undefined;
}
