/**
 * R6 audit handle (task 034) — pin `KafkaSubscriberAdapter.keyForCodec` to
 * the broker-resolved concrete topic.
 *
 * The codec dispatch key MUST always be the concrete topic the message
 * arrived on. KafkaJS resolves RegExp subscriptions to concrete topics at
 * delivery time, so `payload.topic` is always concrete. This test pins that
 * contract so a future contributor can't quietly substitute a subscription
 * pattern or any other broker-side wildcard.
 */

import type { Consumer, EachMessagePayload, Kafka } from "kafkajs";
import { describe, expect, it } from "vitest";
import { KafkaSubscriberAdapter } from "../../packages/adapter-kafka/src/kafka.subscriber.adapter";
import { defaultJsonCodec } from "../../packages/core/src/codecs/json.codec";

function buildAdapter(): KafkaSubscriberAdapter {
	const consumerStub = {
		connect: async () => {},
		disconnect: async () => {},
		subscribe: async () => {},
		run: async () => {},
		stop: async () => {},
		events: {} as Consumer["events"],
		on: () => () => {},
	} as unknown as Consumer;
	const kafkaStub = {} as unknown as Kafka;

	return new KafkaSubscriberAdapter(consumerStub, defaultJsonCodec, {
		kafka: kafkaStub,
		groupId: "test-group",
		autoGeneratedGroupId: true,
	});
}

function buildPayload(topic: string): EachMessagePayload {
	return {
		topic,
		partition: 0,
		message: {
			key: null,
			value: null,
			timestamp: "0",
			size: 0,
			attributes: 0,
			offset: "0",
			headers: undefined,
		},
		heartbeat: async () => {},
		pause: () => () => {},
	} as unknown as EachMessagePayload;
}

interface PrivateKeyForCodec {
	keyForCodec(payload: EachMessagePayload): string;
}

describe("KafkaSubscriberAdapter.keyForCodec (R1 audit)", () => {
	it("returns the concrete payload.topic", () => {
		const adapter = buildAdapter();
		const helper = adapter as unknown as PrivateKeyForCodec;

		expect(helper.keyForCodec(buildPayload("orders.v1"))).toBe("orders.v1");
		expect(helper.keyForCodec(buildPayload("events.payments.usd"))).toBe("events.payments.usd");
	});

	it("returns the broker-resolved topic even when arrived via a RegExp subscription", () => {
		// KafkaJS resolves RegExp subscriptions to concrete topics at delivery.
		// The helper trusts the payload — no pattern reconstruction or fallback.
		const adapter = buildAdapter();
		const helper = adapter as unknown as PrivateKeyForCodec;

		expect(helper.keyForCodec(buildPayload("events.user.signup"))).toBe("events.user.signup");
	});
});
